name: release to dev

on:
  release:
    types: [published]

jobs:
 actions-tagger:
  runs-on: ubuntu-latest
  steps:
   - name: get release
     uses: robinraju/release-downloader@v1.7
     with:
      latest: true
      zipBall: true
   - name: trigger amplify pipeline with webhook
     run: |
         ls *.zip
