name: release to dev

on:
  release:
    types: [published]


jobs:
 actions-tagger:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
     with:
      ref: ${{ github.head_ref }}
   - uses: robinraju/release-downloader@v1.7
     with:
      latest: true
      zipBall: true
   - name: rename
     run: mv $(ls *.zip) release.zip
   - uses: stefanzweifel/git-auto-commit-action@v4
     with:
        commit_message: push new release
